enum UsersTypes {
  GET_ALL_USERS_STARTED = 'GET_ALL_USERS_STARTED',
  GET_ALL_USERS_SUCCESS = 'GET_ALL_USERS_SUCCESS',
  GET_ALL_USERS_ERROR = 'GET_ALL_USERS_ERROR',

  GET_SINGLE_USER_STARTED = 'GET_SINGLE_USER_STARTED',
  GET_SINGLE_USER_SUCCESS = 'GET_SINGLE_USER_SUCCESS',
  GET_SINGLE_USER_ERROR = 'GET_SINGLE_USER_ERROR',

  CREATE_USER_STARTED = 'CREATE_USER_STARTED',
  CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS',
  CREATE_USER_ERROR = 'CREATE_USER_ERROR',

  UPDATE_USER_STARTED = 'UPDATE_USER_STARTED',
  UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS',
  UPDATE_USER_ERROR = 'UPDATE_USER_ERROR',

  DELETE_USER_STARTED = 'DELETE_USER_STARTED',
  DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS',
  DELETE_USER_ERROR = 'DELETE_USER_ERROR',
}

export default UsersTypes
