enum AuthenticationActionTypes {
  GET_ME_DATA_STARTED = 'GET_ME_DATA_STARTED',
  GET_ME_DATA_SUCCESS = 'GET_ME_DATA_SUCCESS',
  GET_ME_DATA_ERROR = 'GET_ME_DATA_ERROR',

  LOGIN_STARTED = 'LOGIN_STARTED',
  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
  LOGIN_ERROR = 'LOGIN_ERROR',

  LOGOUT_STARTED = 'LOGOUT_STARTED',
  LOGOUT_SUCCESS = 'LOGOUT_SUCCESS',
  LOGOUT_ERROR = 'LOGOUT_ERROR',
}

export default AuthenticationActionTypes
