export enum RouteRestrictionLevels {
  NON_AUTH_REQUIRED = 'NON_AUTH_REQUIRED',
  AUTH_REQUIRED = 'AUTH_REQUIRED',
  AUTH_WILL_BLOCK = 'AUTH_WILL_BLOCK',
  AUTH_AND_ROLE_REQUIRED = 'AUTH_AND_ROLE_REQUIRED',
}
